apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {0}
  namespace: {1}
  annotations:
    volume.beta.kubernetes.io/storage-class: gluster-heketi-{1}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {2}
