apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: gluster-heketi-{0}
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "{1}"
  restuser: "admin"
  restuserkey: "admin"
  volumetype: "replicate:{2}"